services:
  - type: web
    name: santa-clara-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn panaderia.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: santa-clara-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: santa-clara-db
    databaseName: panaderia_db
    user: panaderia_user